/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRiskMapRouteImport } from './routes/_app/risk-map'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppPopulationRouteImport } from './routes/_app/population'
import { Route as AppModelRouteImport } from './routes/_app/model'
import { Route as AppFairnessRouteImport } from './routes/_app/fairness'
import { Route as AppExplainabilityRouteImport } from './routes/_app/explainability'
import { Route as AppDoctorRouteImport } from './routes/_app/doctor'
import { Route as AppDeveloperRouteImport } from './routes/_app/developer'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskMapRoute = AppRiskMapRouteImport.update({
  id: '/risk-map',
  path: '/risk-map',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPopulationRoute = AppPopulationRouteImport.update({
  id: '/population',
  path: '/population',
  getParentRoute: () => AppRoute,
} as any)
const AppModelRoute = AppModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AppRoute,
} as any)
const AppFairnessRoute = AppFairnessRouteImport.update({
  id: '/fairness',
  path: '/fairness',
  getParentRoute: () => AppRoute,
} as any)
const AppExplainabilityRoute = AppExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => AppRoute,
} as any)
const AppDoctorRoute = AppDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => AppRoute,
} as any)
const AppDeveloperRoute = AppDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/developer': typeof AppDeveloperRoute
  '/doctor': typeof AppDoctorRoute
  '/explainability': typeof AppExplainabilityRoute
  '/fairness': typeof AppFairnessRoute
  '/model': typeof AppModelRoute
  '/population': typeof AppPopulationRoute
  '/reports': typeof AppReportsRoute
  '/risk-map': typeof AppRiskMapRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/alerts': typeof AppAlertsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/developer': typeof AppDeveloperRoute
  '/doctor': typeof AppDoctorRoute
  '/explainability': typeof AppExplainabilityRoute
  '/fairness': typeof AppFairnessRoute
  '/model': typeof AppModelRoute
  '/population': typeof AppPopulationRoute
  '/reports': typeof AppReportsRoute
  '/risk-map': typeof AppRiskMapRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/developer': typeof AppDeveloperRoute
  '/_app/doctor': typeof AppDoctorRoute
  '/_app/explainability': typeof AppExplainabilityRoute
  '/_app/fairness': typeof AppFairnessRoute
  '/_app/model': typeof AppModelRoute
  '/_app/population': typeof AppPopulationRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/risk-map': typeof AppRiskMapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/developer'
    | '/doctor'
    | '/explainability'
    | '/fairness'
    | '/model'
    | '/population'
    | '/reports'
    | '/risk-map'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/developer'
    | '/doctor'
    | '/explainability'
    | '/fairness'
    | '/model'
    | '/population'
    | '/reports'
    | '/risk-map'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/alerts'
    | '/_app/analytics'
    | '/_app/developer'
    | '/_app/doctor'
    | '/_app/explainability'
    | '/_app/fairness'
    | '/_app/model'
    | '/_app/population'
    | '/_app/reports'
    | '/_app/risk-map'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-map': {
      id: '/_app/risk-map'
      path: '/risk-map'
      fullPath: '/risk-map'
      preLoaderRoute: typeof AppRiskMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/population': {
      id: '/_app/population'
      path: '/population'
      fullPath: '/population'
      preLoaderRoute: typeof AppPopulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/model': {
      id: '/_app/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof AppModelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fairness': {
      id: '/_app/fairness'
      path: '/fairness'
      fullPath: '/fairness'
      preLoaderRoute: typeof AppFairnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explainability': {
      id: '/_app/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof AppExplainabilityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/doctor': {
      id: '/_app/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developer': {
      id: '/_app/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AppDeveloperRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDeveloperRoute: typeof AppDeveloperRoute
  AppDoctorRoute: typeof AppDoctorRoute
  AppExplainabilityRoute: typeof AppExplainabilityRoute
  AppFairnessRoute: typeof AppFairnessRoute
  AppModelRoute: typeof AppModelRoute
  AppPopulationRoute: typeof AppPopulationRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskMapRoute: typeof AppRiskMapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDeveloperRoute: AppDeveloperRoute,
  AppDoctorRoute: AppDoctorRoute,
  AppExplainabilityRoute: AppExplainabilityRoute,
  AppFairnessRoute: AppFairnessRoute,
  AppModelRoute: AppModelRoute,
  AppPopulationRoute: AppPopulationRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskMapRoute: AppRiskMapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
